"""empty message

Revision ID: 44bc65c5ed56
Revises: 15791a4b1d49
Create Date: 2022-06-20 18:59:06.223654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bc65c5ed56'
down_revision = '15791a4b1d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('eye_color', sa.String(length=120), nullable=True),
    sa.Column('hair_color', sa.String(length=120), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('planet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('subscription', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription')
    op.drop_column('user', 'name')
    op.drop_table('people')
    # ### end Alembic commands ###
